profiles:
 username: Marry 
 address: Taipei
 phone: 0900000000
 
 spring:
  ## Freemarker 配置
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
    template-loader-path: classpath:/templates/
  mvc:
    static-path-pattern: /**


spring:
  security:
    oauth2:
      client:
        registration:
         google:
          clientId: 525746979520-i89ckid374pjnhtbjm01obqludure9u4.apps.googleusercontent.com
          clientSecret: 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  
          scope:
           - email
           - profile

